### PR TITLE
Bug Fix: Sorting URI incorrectly removing params

### LINKED ISSUE #47: Index sort mechanism does work when you have more than on column
When you index page has more thank one column, e.g. User name and User role, the sort mechanism seems to fail, other columns will never get sorted.

As far as I can see is something wrong with the `ModelSorter::UriConstructor.new.build_uri_with_cycled_sorting_params` or the view helper `sortable_heading_for`.

screenshot

### PR DESCRIPTION
**Pull request by jordanmaguire**
issue 47_sorting_broken

Fixes #47

### CODE REVIEW

**Comment by osiro** [comment]
Sweet! :+1:

**Comment by osiro** [comment]
@jordanmaguire I think this broken look:

screenshot


I think this fixes the issue:

```ruby
module ApplicationHelper
  def sortable_heading_for(attribute)
    sort_direction = request.query_parameters[:sort_attribute] == attribute.to_s ? request.query_parameters[:sort_direction] : ""
    sortable_uri = ModelSorter::UriConstructor.new.build_uri_with_cycled_sorting_params(attribute, request.path, request.query_parameters)
    link_to(attribute.to_s.titleize, sortable_uri.to_s, class: "sortable #{sort_direction}")
  end
end
```

**Comment by jordanmaguire** [comment]
lol I must have not copied across that change - I'm a dickhead.

**Comment by jordanmaguire** [comment]
I built the initial solution in mulcho and copied it across

**Comment by jordanmaguire** [comment]
I'll add that with correct specs to RT

**Comment by osiro** [comment]
In case you wanna use this specs to cover that change:

```ruby
  describe "#sortable_heading_for" do
    subject { helper.sortable_heading_for(attribute) }
    let(:attribute) { "dongle" }
    let(:stub_request) { instance_double(ActionDispatch::Request) }

    before do
      allow(stub_request).to receive(:path).and_return("x")
      allow(stub_request).to receive(:query_parameters).and_return({sort_direction: "asc"})
      allow(helper).to receive(:request).and_return(stub_request)
    end

    it "returns a link with the sortable URL" do
      expected_uri = "www.jordan_rules.com"
      expect_any_instance_of(ModelSorter::UriConstructor).to receive(:build_uri_with_cycled_sorting_params).and_return(expected_uri)

      should include("href=\"#{expected_uri}\"")
    end

    it "includes the titleized attribute" do
      should include(">Dongle</a>")
    end

    context "when request query parameters contains the sorted attribute" do
      before do
        allow(stub_request).to receive(:query_parameters).and_return({sort_direction: "asc", sort_attribute: attribute })
      end

      it "includes the sort direction as a class" do
        should include("sortable asc")
      end
    end

    context "when request query parameters does not contains the sorted attribute" do
      before do
        allow(stub_request).to receive(:query_parameters).and_return({sort_direction: "asc", sort_attribute: "another_attribute" })
      end

      it "excludes the sort direction as a class" do
        should include("sortable")
        should_not include("sortable asc")
      end
    end
  end
```

**Pull request merged**
