### PR TITLE
DRY controlles by moving sort method to admin::base

### PR DESCRIPTION
**Pull request by osiro**
The `sort` method is gonna be pretty much the same for all other admin controllers, if for some reason you wanna customise it, just override it :)

Will change generators not to generate this piece of code anymore.

### CODE REVIEW

**Comment by jordanmaguire** [comment]
:+1:

**Comment by osiro** [comment]
@jordanmaguire you reckon I should move it down to AppController instead Admin::BaseController?

**Comment by jordanmaguire** [comment]
Nah - leave as is for now (ie: in A::BC)

**Comment by osiro** [comment]
:+1:

**Pull request merged**
