### PR TITLE
Show flash message when fail to create/update

### PR DESCRIPTION
**Pull request by jordanmaguire**
screen shot 2016-04-19 at 12 12 25 pm

### CODE REVIEW

**Comment by BenR1312** [comment]
Looks good man

**Comment by pzi** [comment]
Good 👍

**Comment by pzi** [comment]
Does it need explanation why something could not be created... As a user, I'd feel kinda left in the dark

**Comment by jordanmaguire** [comment]
> 
Does it need explanation why something could not be created... As a user, I'd feel kinda left in the dark

I think the best we can do is: "Object could not be created. See errors below" Or "Please address the errors below"

We don't want to put too much info in the flash

**Pull request merged**
