### PR TITLE
Feature/use semantic ui

### PR DESCRIPTION
**Pull request by pzi**
# Use Semantic UI

The admin and (temporary) public/member pages are being switched over to [Semantic UI](http://semantic-ui.com/).

[Read the docs](http://semantic-ui.com/introduction/getting-started.html) to get started.

## Desktop
image

image

## Mobile
screen shot 2016-09-27 at 15 44 06

### CODE REVIEW

**Comment by jordanmaguire** [comment]
Jesus christ you boned a merge up REAL bad here

**Comment by jordanmaguire** [comment]
I'd be super tempted to squash your commits at this point - even before you handle the merge conflicts

**Comment by jgunnink** [comment]
Looks good 👍 
Still some breaking tests though.

**Comment by jordanmaguire** [comment]
Have fixed issues and put in follow up PR

**Pull request merged**
