### PR TITLE
Add cancel button for users form

### PR DESCRIPTION
**Pull request by jordanmaguire**
screen shot 2015-06-26 at 3 56 19 pm

### CODE REVIEW

**Comment by osiro** [comment]
Nice!

Thinking about add this to generators as well

**Comment by osiro** [comment]
Ohhh fuck... you fast...

Just saw that you've already added to generators, you bitch!

**Comment by pzi** [comment]
That's what's called KISS, my friends.

**Comment by jordanmaguire** [comment]
KIS

**Comment by jordanmaguire** [comment]
is simpler

**Pull request merged**
